export const translations = {
  en: {
    // Homepage & General
    platformName: "PrintWrap Pro",
    homepageTitle: "Your Vision, Expertly Printed & Wrapped.",
    homepageSubtitle:
      "High-quality custom prints and professional car wrapping services in Sweden. Inspired by Vistaprint, powered by innovation.",
    startDesigning: "Start Designing",
    login: "Login",
    signup: "Sign Up",
    viewProducts: "View Products",
    products: "Products",
    dashboard: "Dashboard",
    cart: "Cart",
    checkout: "Checkout",
    logout: "Logout",
    allCategories: "All Categories",
    vat: "VAT (25%)",
    shipping: "Shipping",
    total: "Total",
    price: "Price",
    quantity: "Quantity",
    language: "Language",
    exploreMoreProducts: "Explore More Products",
    trackOrderStatus: "Track Your Order Status",
    trackOrderStatusSignIn: "Track your order status after signing in.",

    // User Accounts
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    customerNumber: "Customer Number",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    invalidCredentials: "Invalid email or password. Please try again.",
    accountCreated: "Account created!",
    welcomeToPlatform: "Welcome to PrintWrap Pro! Your account has been created successfully.",
    signupFailed: "Signup failed",
    failedToCreateAccount: "Failed to create account. Please try again.",
    userAlreadyExists: "User already exists. Please try logging in.",
    loggingIn: "Logging in...",
    creatingAccount: "Creating account...",
    welcomeBack: "Welcome back!",
    loggedInSuccessfully: "You have been successfully logged in.",

    // Dashboards
    clientDashboard: "Client Dashboard",
    savedDesigns: "Saved Designs",
    orderHistory: "Order History",
    billingShippingInfo: "Billing & Shipping Info",
    profile: "Profile",
    adminDashboard: "Admin Dashboard",
    manageUsers: "Manage Users",
    manageProductsPrices: "Manage Products & Prices",
    addTemplate: "Add Template",
    editTemplate: "Edit Template",
    deleteTemplate: "Delete Template",
    templateCreated: "Template '{templateName}' created successfully",
    templateUpdated: "Template '{templateName}' updated successfully",
    templateDeleted: "Template '{templateName}' deleted successfully",
    failedToCreateTemplate: "Failed to create template",
    failedToUpdateTemplate: "Failed to update template",
    failedToDeleteTemplate: "Failed to delete template",
    confirmDeleteTemplate: "Are you sure you want to delete template '{templateName}'?",
    searchTemplates: "Search templates...",
    filterByCategory: "Filter by category",
    allCategories: "All Categories",
    templateName: "Template Name",
    templateImage: "Template Image",
    freeTemplate: "Free Template",
    operationsDashboard: "Operations Dashboard",
    activeOrdersQueue: "Active Orders Queue",
    welcomeBackUser: "Dashboard",
    noDashboardAvailable: "No dashboard available for your role.",
    totalOrders: "Total Orders",
    inQueue: "In Queue",
    inProduction: "In Production",
    completed: "Completed",
    noOrdersYet: "No orders yet",
    startShopping: "Start shopping to see your order history here.",
    createNewDesign: "Create New Design",
    noDesignsFound: "No designs found.",
    startDesigningNow: "Start designing now to see your saved designs here.",
    fullName: "Full Name",
    address: "Address",
    city: "City",
    postalCode: "Postal Code",
    country: "Country",
    phone: "Phone",
    saveChanges: "Save Changes",
    editUser: "Edit User",
    deleteUser: "Delete User",
    confirmDeleteUser: "Are you sure you want to delete this user? This action cannot be undone.",
    userDeleted: "User deleted successfully.",
    failedToDeleteUser: "Failed to delete user. Please try again.",
    userUpdated: "User updated successfully.",
    failedToUpdateUser: "Failed to update user. Please try again.",
    role: "Role",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    searchUsers: "Search users...",
    filterByRole: "Filter by role",
    allRoles: "All Roles",
    userRole: "Role",
    user: "User",
    admin: "Admin",
    operations: "Operations",
    enterProductName: "Enter product name",
    enterProductDescription: "Enter product description",
    updateUser: "Update User",

    // Design Tool
    designTool: "Design Tool",
    uploadImage: "Upload Image (JPG, PNG, SVG)",
    addText: "Add Text",
    textProperties: "Text Properties",
    font: "Font",
    color: "Color",
    size: "Size",
    imageProperties: "Image Properties",
    dragResizeRotate: "Drag, Resize, Rotate",
    importDesign: "Import Design (PDF/AI)",
    previewExport: "Preview & Export",
    downloadPNG: "Download PNG",
    downloadPDF: "Download PDF",
    canvasArea: "Design Canvas",
    designName: "Design Name",
    enterDesignName: "Enter design name",
    designTools: "Design Tools",
    textContent: "Text Content",
    enterYourText: "Enter your text",
    fontSize: "Font Size",
    addImage: "Add Image",
    addShape: "Add Shape",
    elementProperties: "Element Properties",
    xPosition: "X Position",
    yPosition: "Y Position",
    width: "Width",
    height: "Height",
    rotation: "Rotation (degrees)",
    backgroundColor: "Background Color",
    deleteElement: "Delete Element",
    saveDesign: "Save Design",
    exportPNG: "Export PNG",
    exportPDF: "Export PDF",
    clickToSelectElements: "Click on elements to select them. Use the properties panel to modify selected elements.",
    errorEnterText: "Please enter some text first.",
    textAdded: "Text element has been added to your design.",
    errorUploadImage: "Please upload an image first.",
    imageAdded: "Image has been added to your design.",
    shapeAdded: "{shapeType} has been added to your design.",
    elementDeleted: "Selected element has been removed from your design.",
    loginToSaveDesign: "Please log in to save your design.",
    designSaved: '"{designName}" has been saved to your designs.',
    failedToSaveDesign: "Failed to save design. Please try again.",
    pdfExportInfo: "PDF export functionality would be implemented here.",

    // Car Wrap
    carWrapDesigner: "Car Wrap Designer",
    enterLicensePlate: "Enter Swedish License Plate",
    findVehicle: "Find Vehicle",
    vehicleMockup: "Vehicle Mockup",
    applyDesignToWrap: "Apply Design to Wrap",
    bleedGuidelines: "Bleed Guidelines",
    vehicleSelection: "Vehicle Selection",
    swedishLicensePlate: "Swedish License Plate",
    vehicleFound: "Vehicle Found!",
    foundVehicle: "Found {make} {model}",
    vehicleNotFound: "Vehicle Not Found",
    defaultVehicleTemplate:
      "Using default vehicle template. In a real system, this would connect to vehicle databases.",
    designUpload: "Design Upload",
    uploadDesign: "Upload Design",
    applyToVehicle: "Apply to Vehicle",
    designApplied: "Your design has been applied to the vehicle wrap.",
    designProperties: "Design Properties",
    opacity: "Opacity",
    blendMode: "Blend Mode",
    removeDesign: "Remove Design",
    designRemoved: "The selected design has been removed from the wrap.",
    viewControls: "View Controls",
    showGrid: "Show Grid",
    zoomLevel: "Zoom Level",
    designExported: "Your car wrap design has been exported as PNG.",
    clickToSelectDesigns: "Click on designs to select them. Use the properties panel to modify selected designs.",
    designGuidelines: "Car Wrap Design Guidelines",
    designRequirements: "Design Requirements:",
    minResolution: "Minimum 300 DPI resolution",
    cmykColorMode: "CMYK color mode for printing",
    bleedArea: "3mm bleed area around edges",
    vectorGraphics: "Vector graphics preferred",
    installationNotes: "Installation Notes:",
    vehicleCurves: "Consider vehicle curves and contours",
    doorHandles: "Account for door handles and mirrors",
    testPrint: "Test print small sections first",
    professionalInstallation: "Professional installation recommended",

    // Products & Ordering
    productCategories: "Product Categories",
    flyers: "Flyers",
    businessCards: "Business Cards",
    stickers: "Stickers",
    carWraps: "Car Wraps",
    decals: "Decals",
    apparel: "Apparel",
    promotionalItems: "Promotional Items",
    addToCart: "Add to Cart",
    shippingOptions: "Shipping Options",
    standardShipping: "Standard (5-7 days)",
    expressShipping: "Express (2-3 days)",
    paymentMethod: "Payment Method",
    payWithSwish: "Pay with Swish",
    payWithCard: "Pay with Card",
    payWithKlarna: "Pay with Klarna",
    payNow: "Pay Now",
    orderConfirmation: "Order Confirmation",
    thankYouForOrder: "Thank you for your order!",
    orderSummaryEmail: "A summary of your order and a PDF proof (simulated) has been sent to your email.",
    backToHome: "Back to Home",
    addedToCart: "Added to cart",
    itemAddedToCart: "{productName} has been added to your cart.",
    outOfStock: "Out of Stock",
    searchProducts: "Search products...",
    filterByCategory: "Filter by category",
    noProductsFound: "No products found matching your criteria.",
    adjustSearchFilter: "Try adjusting your search or filter criteria.",
    addProduct: "Add New Product",
    productName: "Product Name",
    category: "Category",
    description: "Description",
    productImage: "Product Image",
    cancel: "Cancel",
    createProduct: "Create Product",
    creating: "Creating...",
    productCreated: "{productName} has been created successfully.",
    failedToCreateProduct: "Failed to create product. Please try again.",
    editProduct: "Edit Product",
    updateProduct: "Update Product",
    updating: "Updating...",
    productUpdated: "{productName} has been updated successfully.",
    failedToUpdateProduct: "Failed to update product. Please try again.",
    deleteProduct: "Delete Product",
    confirmDeleteProduct: 'Are you sure you want to delete "{productName}"? This action cannot be undone.',
    productDeleted: "{productName} has been deleted successfully.",
    failedToDeleteProduct: "Failed to delete product. Please try again.",
    noProductsYet: "No products found",
    getStartedAddProduct: "Get started by adding your first product.",
    addYourFirstProduct: "Add Your First Product",
    orderSummary: "Order Summary",
    processing: "Processing...",
    paymentFailed: "Payment failed:",
    statusUpdated: "Status Updated",
    orderStatusChanged: "Order {orderId} status changed to {newStatus}",
    failedToUpdateOrder: "Failed to update order status. Please try again.",
    exportStarted: "Export Started",
    printFilePrepared: "Print file for order {orderId} is being prepared for download.",
    noOrdersInQueue: "No orders in queue",
    allOrdersProcessed: "All orders have been processed.",
    updateStatus: "Update Status",
    exportPrintFile: "Export Print File",
    orderId: "Order ID",
    customer: "Customer",
    date: "Date",
    status: "Status",
    total: "Total",
    items: "Items",
    loadingProducts: "Loading products...",
    yourCartIsEmpty: "Your cart is currently empty.",
    browseProducts: "Browse Products",
    mockCardPayment: "Mock card payment form here...",
    mockSwishInstructions: "Mock Swish instructions here...",
    mockKlarnaOptions: "Mock Klarna options here...",

    // General UI
    loading: "Loading...",
    edit: "Edit",
    delete: "Delete",
    duplicate: "Duplicate",
    modified: "Modified",
    draft: "Draft",
    inReview: "In Review",
    completedStatus: "Completed",
    cancel: "Cancel",
    chooseFile: "Choose File",
    dropImageHere: "Drop your image here, or click to browse",
    imageFormats: "PNG, JPG, GIF up to {maxSize}MB",
    selectCategory: "Select a category",
    priceSEK: "Price (SEK)",
    productNameRequired: "Product name is required",
    nameMinLength: "Name must be at least 2 characters",
    priceRequired: "Price is required",
    priceGreaterThanZero: "Price must be greater than 0",
    categoryRequired: "Category is required",
  },
  sv: {
    // Swedish translations (abbreviated for space)
    platformName: "PrintWrap Pro",
    homepageTitle: "Din Vision, Expertmässigt Tryckt & Folierad.",
    homepageSubtitle: "Högkvalitativa anpassade tryck och professionella bilfolieringstjänster i Sverige.",
    startDesigning: "Börja Designa",
    login: "Logga In",
    signup: "Registrera Dig",
    viewProducts: "Visa Produkter",
    products: "Produkter",
    dashboard: "Kontrollpanel",
    cart: "Varukorg",
    checkout: "Kassa",
    logout: "Logga Ut",
    allCategories: "Alla Kategorier",
    vat: "Moms (25%)",
    shipping: "Frakt",
    total: "Totalt",
    price: "Pris",
    quantity: "Antal",
    language: "Språk",
    exploreMoreProducts: "Utforska Fler Produkter",
    trackOrderStatus: "Spåra Din Orderstatus",
    trackOrderStatusSignIn: "Spåra din orderstatus efter inloggning.",

    // User Accounts
    email: "E-post",
    password: "Lösenord",
    confirmPassword: "Bekräfta Lösenord",
    customerNumber: "Kundnummer",
    alreadyHaveAccount: "Har du redan ett konto?",
    dontHaveAccount: "Har du inget konto?",
    invalidCredentials: "Ogiltig e-post eller lösenord. Försök igen.",
    accountCreated: "Konto skapat!",
    welcomeToPlatform: "Välkommen till PrintWrap Pro! Ditt konto har skapats.",
    signupFailed: "Registrering misslyckades",
    failedToCreateAccount: "Kunde inte skapa konto. Försök igen.",
    userAlreadyExists: "Användaren finns redan. Försök logga in.",
    loggingIn: "Loggar in...",
    creatingAccount: "Skapar konto...",
    welcomeBack: "Välkommen tillbaka!",
    loggedInSuccessfully: "Du har loggats in framgångsrikt.",

    // Dashboards
    clientDashboard: "Kundpanel",
    savedDesigns: "Sparade Designer",
    orderHistory: "Orderhistorik",
    billingShippingInfo: "Fakturerings- & Leveransinfo",
    profile: "Profil",
    adminDashboard: "Adminpanel",
    manageUsers: "Hantera Användare",
    manageProductsPrices: "Hantera Produkter & Priser",
    addTemplate: "Lägg Till Mall",
    editTemplate: "Redigera Mall",
    deleteTemplate: "Ta Bort Mall",
    templateCreated: "Mall '{templateName}' skapad.",
    templateUpdated: "Mall '{templateName}' uppdaterad.",
    templateDeleted: "Mall '{templateName}' borttagen.",
    failedToCreateTemplate: "Kunde inte skapa mall.",
    failedToUpdateTemplate: "Kunde inte uppdatera mall.",
    failedToDeleteTemplate: "Kunde inte ta bort mall.",
    confirmDeleteTemplate: "Är du säker på att du vill ta bort mallen '{templateName}'?",
    searchTemplates: "Sök mallar...",
    filterByCategory: "Filtrera efter kategori",
    allCategories: "Alla Kategorier",
    templateName: "Mallnamn",
    templateImage: "Mallbild",
    freeTemplate: "Gratis Mall",
    operationsDashboard: "Operationspanel",
    activeOrdersQueue: "Aktiv Orderkö",
    welcomeBackUser: "Instrumentpanel",
    noDashboardAvailable: "Ingen kontrollpanel tillgänglig för din roll.",
    totalOrders: "Totala Beställningar",
    inQueue: "I Kö",
    inProduction: "I Produktion",
    completed: "Färdigställda",
    noOrdersYet: "Inga beställningar ännu",
    startShopping: "Börja handla för att se din orderhistorik här.",
    createNewDesign: "Skapa Ny Design",
    noDesignsFound: "Inga designer hittades.",
    startDesigningNow: "Börja designa nu för att se dina sparade designer här.",
    fullName: "Fullständigt Namn",
    address: "Adress",
    city: "Stad",
    postalCode: "Postnummer",
    country: "Land",
    phone: "Telefon",
    saveChanges: "Spara Ändringar",
    editUser: "Redigera Användare",
    deleteUser: "Ta Bort Användare",
    confirmDeleteUser: "Är du säker på att du vill ta bort den här användaren? Detta kan inte ångras.",
    userDeleted: "Användaren har tagits bort.",
    failedToDeleteUser: "Kunde inte ta bort användaren. Försök igen.",
    userUpdated: "Användaren har uppdaterats.",
    failedToUpdateUser: "Kunde inte uppdatera användaren. Försök igen.",
    role: "Roll",
    actions: "Åtgärder",
    edit: "Redigera",
    delete: "Ta Bort",
    searchUsers: "Sök användare...",
    filterByRole: "Filtrera efter roll",
    allRoles: "Alla Roller",
    userRole: "Roll",
    user: "Användare",
    admin: "Admin",
    operations: "Drift",
    enterProductName: "Ange produktnamn",
    enterProductDescription: "Ange produktbeskrivning",
    updateUser: "Uppdatera Användare",

    // Design Tool
    designTool: "Designverktyg",
    uploadImage: "Ladda Upp Bild (JPG, PNG, SVG)",
    addText: "Lägg Till Text",
    textProperties: "Textegenskaper",
    font: "Typsnitt",
    color: "Färg",
    size: "Storlek",
    imageProperties: "Bildegenskaper",
    dragResizeRotate: "Dra, Ändra Storlek, Rotera",
    importDesign: "Importera Design (PDF/AI)",
    previewExport: "Förhandsgranska & Exportera",
    downloadPNG: "Ladda Ner PNG",
    downloadPDF: "Ladda Ner PDF",
    canvasArea: "Designyta",
    designName: "Designnamn",
    enterDesignName: "Ange designnamn",
    designTools: "Designverktyg",
    textContent: "Textinnehåll",
    enterYourText: "Ange din text",
    fontSize: "Teckenstorlek",
    addImage: "Lägg Till Bild",
    addShape: "Lägg Till Form",
    elementProperties: "Elementegenskaper",
    xPosition: "X-position",
    yPosition: "Y-position",
    width: "Bredd",
    height: "Höjd",
    rotation: "Rotation (grader)",
    backgroundColor: "Bakgrundsfärg",
    deleteElement: "Ta Bort Element",
    saveDesign: "Spara Design",
    exportPNG: "Exportera PNG",
    exportPDF: "Exportera PDF",
    clickToSelectElements: "Klicka på element för att välja dem. Använd egenskapspanelen för att ändra valda element.",
    errorEnterText: "Vänligen ange text först.",
    textAdded: "Textelement har lagts till i din design.",
    errorUploadImage: "Vänligen ladda upp en bild först.",
    imageAdded: "Bild har lagts till i din design.",
    shapeAdded: "{shapeType} har lagts till i din design.",
    elementDeleted: "Valt element har tagits bort från din design.",
    loginToSaveDesign: "Vänligen logga in för att spara din design.",
    designSaved: '"{designName}" har sparats i dina designer.',
    failedToSaveDesign: "Kunde inte spara design. Försök igen.",
    pdfExportInfo: "PDF-exportfunktion skulle implementeras här.",

    // Car Wrap
    carWrapDesigner: "Bilfolieringsdesigner",
    enterLicensePlate: "Ange Svenskt Registreringsnummer",
    findVehicle: "Hitta Fordon",
    vehicleMockup: "Fordonssimulering",
    applyDesignToWrap: "Applicera Design på Folie",
    bleedGuidelines: "Utfallsmarginaler",
    vehicleSelection: "Fordonval",
    swedishLicensePlate: "Svenskt Registreringsnummer",
    vehicleFound: "Fordon Hittades!",
    foundVehicle: "Hittade {make} {model}",
    vehicleNotFound: "Fordon Hittades Inte",
    defaultVehicleTemplate:
      "Använder standardfordonsmall. I ett verkligt system skulle detta ansluta till fordonsdatabaser.",
    designUpload: "Designuppladdning",
    uploadDesign: "Ladda Upp Design",
    applyToVehicle: "Applicera på Fordon",
    designApplied: "Din design har applicerats på bilfolien.",
    designProperties: "Designegenskaper",
    opacity: "Opacitet",
    blendMode: "Blandningsläge",
    removeDesign: "Ta Bort Design",
    designRemoved: "Den valda designen har tagits bort från folien.",
    viewControls: "Visningskontroller",
    showGrid: "Visa Rutnät",
    zoomLevel: "Zoomnivå",
    designExported: "Din bilfoliedesign har exporterats som PNG.",
    clickToSelectDesigns: "Klicka på designer för att välja dem. Använd egenskapspanelen för att ändra valda designer.",
    designGuidelines: "Riktlinjer för Bilfoliedesign",
    designRequirements: "Designkrav:",
    minResolution: "Minst 300 DPI upplösning",
    cmykColorMode: "CMYK färgläge för utskrift",
    bleedArea: "3mm utfallsmarginal runt kanterna",
    vectorGraphics: "Vektorbaserad grafik föredras",
    installationNotes: "Installationsanmärkningar:",
    vehicleCurves: "Tänk på fordonets kurvor och konturer",
    doorHandles: "Ta hänsyn till dörrhandtag och speglar",
    testPrint: "Testa att skriva ut små sektioner först",
    professionalInstallation: "Professionell installation rekommenderas",

    // Products & Ordering
    productCategories: "Produktkategorier",
    flyers: "Flyers",
    businessCards: "Visitkort",
    stickers: "Klistermärken",
    carWraps: "Bilfoliering",
    decals: "Dekaler",
    apparel: "Kläder",
    promotionalItems: "Kampanjartiklar",
    addToCart: "Lägg i Varukorg",
    shippingOptions: "Fraktalternativ",
    standardShipping: "Standard (5-7 dagar)",
    expressShipping: "Express (2-3 dagar)",
    paymentMethod: "Betalningsmetod",
    payWithSwish: "Betala med Swish",
    payWithCard: "Betala med Kort",
    payWithKlarna: "Betala med Klarna",
    payNow: "Betala Nu",
    orderConfirmation: "Orderbekräftelse",
    thankYouForOrder: "Tack för din beställning!",
    orderSummaryEmail:
      "En sammanfattning av din beställning och ett PDF-korrektur (simulerat) har skickats till din e-post.",
    backToHome: "Tillbaka till Startsidan",
    addedToCart: "Lades till i varukorgen",
    itemAddedToCart: "{productName} har lagts till i din varukorg.",
    outOfStock: "Slut i lager",
    searchProducts: "Sök produkter...",
    filterByCategory: "Filtrera efter kategori",
    noProductsFound: "Inga produkter hittades som matchar dina kriterier.",
    adjustSearchFilter: "Försök justera din sökning eller filterkriterier.",
    addProduct: "Lägg till Ny Produkt",
    productName: "Produktnamn",
    category: "Kategori",
    description: "Beskrivning",
    productImage: "Produktbild",
    cancel: "Avbryt",
    createProduct: "Skapa Produkt",
    creating: "Skapar...",
    productCreated: "{productName} har skapats.",
    failedToCreateProduct: "Kunde inte skapa produkt. Försök igen.",
    editProduct: "Redigera Produkt",
    updateProduct: "Uppdatera Produkt",
    updating: "Uppdaterar...",
    productUpdated: "{productName} har uppdaterats.",
    failedToUpdateProduct: "Kunde inte uppdatera produkt. Försök igen.",
    deleteProduct: "Ta Bort Produkt",
    confirmDeleteProduct: 'Är du säker på att du vill ta bort "{productName}"? Detta kan inte ångras.',
    productDeleted: "{productName} har tagits bort.",
    failedToDeleteProduct: "Kunde inte ta bort produkt. Försök igen.",
    noProductsYet: "Inga produkter hittades",
    getStartedAddProduct: "Kom igång genom att lägga till din första produkt.",
    addYourFirstProduct: "Lägg till Din Första Produkt",
    orderSummary: "Ordersammanfattning",
    processing: "Bearbetar...",
    paymentFailed: "Betalning misslyckades:",
    statusUpdated: "Status Uppdaterad",
    orderStatusChanged: "Order {orderId} status ändrad till {newStatus}",
    failedToUpdateOrder: "Kunde inte uppdatera orderstatus. Försök igen.",
    exportStarted: "Export Startad",
    printFilePrepared: "Utskriftsfil för order {orderId} förbereds för nedladdning.",
    noOrdersInQueue: "Inga ordrar i kö",
    allOrdersProcessed: "Alla ordrar har behandlats.",
    updateStatus: "Uppdatera Status",
    exportPrintFile: "Exportera Utskriftsfil",
    orderId: "Order-ID",
    customer: "Kund",
    date: "Datum",
    status: "Status",
    total: "Totalt",
    items: "Artiklar",
    loadingProducts: "Laddar produkter...",
    yourCartIsEmpty: "Din varukorg är tom.",
    browseProducts: "Bläddra Produkter",
    mockCardPayment: "Simulerad kortbetalningsformulär här...",
    mockSwishInstructions: "Simulerade Swish-instruktioner här...",
    mockKlarnaOptions: "Simulerade Klarna-alternativ här...",

    // General UI
    loading: "Laddar...",
    edit: "Redigera",
    delete: "Ta Bort",
    duplicate: "Duplicera",
    modified: "Ändrad",
    draft: "Utkast",
    inReview: "Under Granskning",
    completedStatus: "Färdigställd",
    cancel: "Avbryt",
    chooseFile: "Välj Fil",
    dropImageHere: "Släpp din bild här, eller klicka för att bläddra",
    imageFormats: "PNG, JPG, GIF upp till {maxSize}MB",
    selectCategory: "Välj en kategori",
    priceSEK: "Pris (SEK)",
    productNameRequired: "Produktnamn krävs",
    nameMinLength: "Namnet måste vara minst 2 tecken",
    priceRequired: "Pris krävs",
    priceGreaterThanZero: "Priset måste vara större än 0",
    categoryRequired: "Kategori krävs",
  },
}

export const productCategories = [
  { id: "all", name: (t: any) => t.allCategories },
  { id: "flyers", name: (t: any) => t.flyers },
  { id: "business-cards", name: (t: any) => t.businessCards },
  { id: "stickers", name: (t: any) => t.stickers },
  { id: "car-wraps", name: (t: any) => t.carWraps },
  { id: "decals", name: (t: any) => t.decals },
  { id: "apparel", name: (t: any) => t.apparel },
  { id: "promotional-items", name: (t: any) => t.promotionalItems },
]

export const carDatabase = {
  "ABC 123": { make: "Volvo", model: "V60", svgPath: "/placeholder.svg?height=300&width=500" },
  "DEF 456": { make: "Saab", model: "9-3", svgPath: "/placeholder.svg?height=300&width=500" },
  "GHI 789": { make: "Tesla", model: "Model Y", svgPath: "/placeholder.svg?height=300&width=500" },
}

export const fonts = ["Arial", "Verdana", "Times New Roman", "Courier New", "Georgia", "Impact"]
export const colors = [
  "#000000",
  "#FF0000",
  "#00FF00",
  "#0000FF",
  "#FFFF00",
  "#FF00FF",
  "#00FFFF",
  "#808080",
  "#FFA500",
  "#800080",
]
